name: Build and Release WinForms

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configurar NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restaurar paquetes NuGet
        run: nuget restore AppTaller.csproj

      - name: Compilar proyecto
        run: msbuild AppTaller.csproj /p:Configuration=Release

      - name: Crear carpeta publish
        run: mkdir publish

      - name: Copiar archivos
        run: |
          xcopy /E /I AppTaller\bin\Release publish

      - name: Crear version.txt
        run: echo %date% %time% > publish/version.txt
        shell: cmd

      - name: Subir artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinFormsBuild
          path: publish