name: Build and Release WinForms

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar proyecto
        run: dotnet build --configuration Release

      - name: Publicar aplicación
        run: dotnet publish -c Release -o publish

      - name: Crear version.txt
        run: echo %date% %time% > publish/version.txt
        shell: cmd

      - name: Subir artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinFormsBuild
          path: publish